import '@/styles/globals.css';

import { type Metadata } from 'next';
import { Geist } from 'next/font/google';

import { TRPCReactProvider } from '@/trpc/react';
import { LayoutWrapper } from '@/components/layout-wrapper';

export const metadata: Metadata = {
    title: 'Amnezia Panel',
    description: 'Generated by slowy19',
    icons: [{ rel: 'icon', url: '/favicon.ico' }],
};

const geist = Geist({
    subsets: ['latin'],
    variable: '--font-geist-sans',
});

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en" className={`${geist.variable}`}>
            <body>
                <TRPCReactProvider>
                    <LayoutWrapper>{children}</LayoutWrapper>
                </TRPCReactProvider>
            </body>
        </html>
    );
}
